### PR TITLE
Raw and Combined Output for Sources

### LINKED ISSUE #4: Process Source Documents with Phrases Tool
The source documents in the repository should be processed with the `phrases` tool; the output of that processing should be saved in the repository (for archival purposes). Once that is done (this issue), the output can be cleaned up and used to help guide domain modeling (see FreeAndFair/TuskMobileVoting#35).

### PR DESCRIPTION
**Pull request by dmzimmerman**
This PR has the raw and combined output for the ~~initial tranche of~~ sources listed in the BibTeX that is also part of the PR. Note that there is also a set of "cleaned" output - I used AI tooling to get rid of obviously bad entries and consolidate verbs (it was not very useful at consolidating nouns, though). We can use the cleaned output for our concept analysis work.

Once we determine that the set of sources in this PR is complete, we can merge it. It will then close #4. 

~~Note that this PR is based on #6, and cannot be merged to `main` before #6 is merged (and may have to be rebased on whatever gets merged from #6, but that's easy as it doesn't change any files changed by #6) - it's currently set to merge to #6's branch, and when #6 is merged to `main`, the merge target will change automatically to `main`.~~ This PR is now based on `main`.

Note also that I've tagged reviewers here primarily for the purpose of checking the completeness of the BibTeX (and thus the sources); there is no practical way, really, for anybody to review the tool outputs.

(for automation)
Closes #4

### CODE REVIEW

**Comment by dmzimmerman** [comment]
I have processed all the sources in `sources.bib` (including the paper draft by Wikström and Ruescas) plus the current draft of the EVS book, and generated combined histograms for the sources with and without the EVS book histograms incorporated. I believe this can be considered "done" at this point, and we can use the combined output to sanity check for missing concepts in the domain model.

**Comment by kiniry** [comment]
The BibTeX validates, `process_sources.sh` and `combine_histograms.py` look good, etc.  We should probably tag exactly which version/commit of the EVS book this data set traces too.

**Review by kiniry — APPROVED** [review]
LGTM

**Review by lukemmyers — APPROVED** [review]
The BibTeX file representing the source documents for this analysis appears to be complete to me. The updates to the README reflect the state of the repository after this PR is merged. I see you also noted which version of the EVS book is included. The changes to the shell script to avoid processing BibTeX are a good addition. This all looks good to me.

**Pull request merged**
